apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ph-ee-connector-airtel
  title: PH Airtel Connector
  description: Zeebe connector integrating with Airtel Money APIs for mobile money payments and loan repayments
  annotations:
    github.com/project-slug: one-acre-fund/ph-ee-connector-airtel
    backstage.io/kubernetes-id: ph-ee-connector-airtel
    sonarqube.org/project-key: one-acre-fund_ph-ee-connector-airtel
    backstage.io/code-coverage: sonarqube
    backstage.io/kubernetes-label-selector: 'app=ph-ee-connector-airtel'
  tags:
    - java
    - zeebe-connector
    - payment-hub
    - paymenthub
    - airtel
    - mno
    - mobile-money
  links:
    - url: https://sonarcloud.io/summary/new_code?id=one-acre-fund_ph-ee-connector-airtel
      title: Code Quality Dashboard
      icon: dashboard
    - url: https://ph-web.oneacrefund.org
      title: Production Environment
      icon: globe
    - url: https://elastic.oneacrefund.org/app/apm/services/ph-ee-connector-mno-airtel
      title: Elastic APM Dashboard
      icon: globe
    - url: https://elastic.oneacrefund.org/app/r/s/UUbNh
      title: Application logs
      icon: globe
    - url: https://elastic.oneacrefund.org/app/r/s/CgjiD
      title: Kong Ingress logs
      icon: globe
    - url: https://github.com/one-acre-fund/ph-ee-connector-airtel/blob/main/.github/workflows/build.yaml
      title: Build Pipeline
      icon: build
spec:
  type: service
  lifecycle: production
  owner: group:default/credits-and-payments
  system: connectors
  consumesApis:
    - zeebe-gateway-grpc-api
  dependsOn:
    - resource:default/zeebe-cluster
