apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ph-ee-connector-airtel"
  labels:
    app: ph-ee-connector-airtel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-connector-airtel
  template:
    metadata:
      labels:
        app: ph-ee-connector-airtel
    spec:
      containers:
        - name: ph-ee-connector-airtel
          image: "airtel:0.1.1"
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 60
            initialDelaySeconds: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 60
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            failureThreshold: 30
            periodSeconds: 5
          ports:
            - containerPort: 5000
          env:
            - name: "ZEEBE_BROKER_CONTACTPOINT"
              value: "localhost:26500"
            - name: "SKIP_ENABLED"
              value: "true"
            - name: "AIRTEL_API_BASE-URL"
              value: "localhost:8080"
            - name: "AIRTEL_API_AUTH-ENDPOINT"
              value: "localhost:8080"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ph-ee-connector-airtel
  name: ph-ee-connector-airtel
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ph-ee-connector-airtel
  sessionAffinity: None
  type: ClusterIP